spring:
  application:
    name: personal-task-manager-api
#  jackson:
#    deserialization:
#      adjust-dates-to-context-time-zone: false
  security:
    name: admin
    password: mojehaslo123
  datasource:
#    url: jdbc:h2:mem:testdb
#    DB_CLOSE_DELAY: -1
#    DB_CLOSE_ON_EXIT: FALSE
#    AUTO_RECONNECT: TRUE
    MODE: PostgreSQL